#travis-ci continuous integration test set up  
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7" 
  - "3.8"
  - "3.9"
#  - "3.10.0"  # fails in travis-ci 
  
# command to install dependencies
before-install:
  - pip install poetry
  
install: 
  #- "pip install -U pytest"
  #- "pip install 'coverage<4'"
  - poetry add pytest coveralls
  - poetry update
  - poetry build

# command to run tests
script: 
  - tox
  #- pytest
  
#code coverage
after_success:
  #- coveralls