#travis-ci continuous integration test set up  
language: python
python:
  - "3.6"
  - "3.7" 
  - "3.8"
  - "3.9"
  - "3.10"

# command to install dependencies
before-install:
  - pip install poetry
  
install: 
  #- "pip install -U pytest"
  #- "pip install 'coverage<4'"
  - poetry add pytest pytest-cov coveralls
  - poetry update
  - poetry build

# command to run tests
script: 
  - poetry run pytest
  #- pytest
  #- coverage run --source fifostr -m pytest  

#code coverage
after_success:
  #- coveralls